easy_admin:
    site_name: 'Action 4 Malawi'
    design:
        brand_color: '#0295d9'
        color_scheme: 'light'
    entities:
        PageContent:
            class: App\Entity\PageContent
            disabled_actions: ['new', 'delete']
            label: 'Page Text'
            list:
                title: "Page Text"
                fields:
                    - 'page'
            form:
                fields:
                    - { property: 'content', type: 'ckeditor' }
        GalleryImage:
            class: App\Entity\GalleryImage
            label: 'Gallery'
            list:
                title: "Gallery Images"
                fields:
                    - { property: 'path', type: 'image', base_path: '%app.path.gallery%' }
                    - 'caption'
            show:
                fields:
                    - { property: 'path', type: 'image', base_path: '%app.path.gallery%' }
                    - 'caption'
            form:
                fields:
                    - { property: 'file', type: 'file' }
                    - 'caption'

