liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/images/gallery"
    filter_sets:
        thumbnail:
            jpeg_quality:          20
            png_compression_level: 10
            filters:
                upscale:
                    min: [500, 500]
                thumbnail:
                    size:          [500, 500]
                    mode:          inset
                    allow_upscale: true
        thumbnail_square:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                upscale:
                    min: [510, 510]
                thumbnail:
                    size:          [510, 510]
                    mode:          outbound
                    allow_upscale: true
