parameters:
    app.path.gallery: '/images/gallery'
vich_uploader:
    db_driver: orm
    mappings:
        gallery:
            uri_prefix: '%app.path.gallery%'
            upload_destination: '%kernel.project_dir%/public%app.path.gallery%'
